CREATE TABLE "GCG_5631_ToUpload" (
 "FileHeader" INTEGER,
 "Num" INTEGER,
 "Type" VARCHAR(7),
 "Priority" VARCHAR(10),
 "Part" VARCHAR(20),
 "OpenQty" INTEGER,
 "OrderID" VARCHAR(15),
 "ItemID" VARCHAR(15),
 "Locn" CHAR(4),
 "ReqDate" DATE,
 "NumFromForecast" INTEGER,
 "A_1" CHAR(1),
 "KeyFigure" VARCHAR(50),
 "UploadGridNum" INTEGER );
